CREATE DATABASE IF NOT EXISTS db_kasir;

USE db_kasir;

CREATE TABLE IF NOT EXISTS kategori(
 id_kategori BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 nama_kategori VARCHAR(255) NOT NULL,
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS supplier(
 id_supplier BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 nama_supplier VARCHAR(255) NOT NULL,
 alamat VARCHAR(255) NOT NULL,
 telepon VARCHAR(20) NOT NULL,
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS pelanggan(
 id_pelanggan BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 nama_pelanggan VARCHAR(255) NOT NULL,
 alamat VARCHAR(255) NOT NULL,
 telepon VARCHAR(20) NOT NULL,
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS produk(
 id_produk BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 nama_produk VARCHAR (255) NOT NULL,
 harga DECIMAL (10,2) NOT NULL,
 stok INTEGER NOT NULL,
 id_kategori BIGINT NOT NULL,
 id_supplier BIGINT NOT NULL,
 barcode VARCHAR(50),
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (id_kategori) REFERENCES kategori(id_kategori),
 FOREIGN KEY (id_supplier) REFERENCES supplier(id_supplier)
);

CREATE TABLE IF NOT EXISTS karyawan(
 id_karyawan BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 nama_karyawan VARCHAR(255) NOT NULL,
 username VARCHAR(100) NOT NULL,
 PASSWORD VARCHAR(255) NOT NULL,
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS penjualan(
 id_penjualan BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 id_karyawan BIGINT NOT NULL,
 id_pelanggan BIGINT NOT NULL,
 tanggal DATE NOT NULL,
 total_harga DECIMAL(10,2) NOT NULL,
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (id_karyawan) REFERENCES karyawan(id_karyawan),
 FOREIGN KEY (id_pelanggan) REFERENCES pelanggan(id_pelanggan)
);

CREATE TABLE IF NOT EXISTS detail_penjualan(
 id_detail_penjualan BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 id_penjualan BIGINT NOT NULL,
 id_produk BIGINT NOT NULL,
 jumlah INTEGER NOT NULL,
 harga_satuan DECIMAL(10,2) NOT NULL,
 subtotal DECIMAL(10,2) NOT NULL,
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (id_penjualan) REFERENCES penjualan(id_penjualan),
 FOREIGN KEY (id_produk) REFERENCES produk(id_produk)
);

CREATE TABLE IF NOT EXISTS retur_penjualan(
 id_retur_penjualan BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 id_karyawan BIGINT NOT NULL,
 id_penjualan BIGINT NOT NULL,
 tanggal_retur DATE NOT NULL,
 alasan VARCHAR(255) NOT NULL,
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (id_karyawan) REFERENCES karyawan(id_karyawan),
 FOREIGN KEY (id_penjualan) REFERENCES penjualan(id_penjualan)
);

CREATE TABLE IF NOT EXISTS pembelian(
 id_pembelian BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 id_karyawan BIGINT NOT NULL,
 id_supplier BIGINT NOT NULL,
 tanggal DATE NOT NULL,
 total_harga DECIMAL(10,2) NOT NULL,
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (id_karyawan) REFERENCES karyawan(id_karyawan),
 FOREIGN KEY (id_supplier) REFERENCES supplier(id_supplier)
);

CREATE TABLE IF NOT EXISTS detail_pembelian(
 id_detail_pembelian BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 id_pembelian BIGINT NOT NULL,
 id_produk BIGINT NOT NULL,
 jumlah INTEGER NOT NULL,
 harga_satuan DECIMAL(10,2) NOT NULL,
 subtotal DECIMAL(10,2) NOT NULL,
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (id_pembelian) REFERENCES pembelian(id_pembelian),
 FOREIGN KEY (id_produk) REFERENCES produk(id_produk)
);

CREATE TABLE IF NOT EXISTS retur_pembelian(
 id_retur_pembelian BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 id_karyawan BIGINT NOT NULL,
 id_pembelian BIGINT NOT NULL,
 tanggal_retur DATE NOT NULL,
 alasan VARCHAR(255) NOT NULL,
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (id_karyawan) REFERENCES karyawan(id_karyawan),
 FOREIGN KEY (id_pembelian) REFERENCES pembelian(id_pembelian)
);
